# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6.12'
          architecture: x64
      
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            kfp==1.1.2

      - name: run pipeline to kubeflow
        run: python kubeflow_pipeline/pipeline.py
