
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Images
        run: |
          docker build kubeflow_pipeline/peprocess -t kaejong/mnist-pre-data
          docker push kaejong/mnist-pre-data
          docker build kubeflow_pipeline/valid_data -t kaejong/mnist-val-data
          docker push kaejong/mnist-val-data
          docker build kubeflow_pipeline/train_model -t kaejong/mnist-train-model
          docker push kaejong/mnist-train-model
          docker build kubeflow_pipeline/embedding -t kaejong/mnist-embedding
          docker push kaejong/mnist-embedding
          docker build kubeflow_pipeline/train_faiss -t kaejong/mnist-train-faiss
          docker push kaejong/mnist-train-faiss
          docker build kubeflow_pipeline/analysis_model -t kaejong/mnist-analysis
          docker push kaejong/mnist-analysis
          docker build kubeflow_pipeline/deploy -t kaejong/mnist-deploy
          docker push kaejong/mnist-deploy
        
      
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_CHANNEL: mnist-project
          SLACK_MESSAGE: 'Build/Push Images :building_construction: - ${{job.status}}'
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          
